version: "3.9"

services:
  userdb:
    image: postgres:15.4
    container_name: user_management
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_management
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d user_management"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-management-service:
    build: .
    container_name: user-management-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://userdb:5432/user_management
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      userdb:
        condition: service_healthy
