services:
  userdb:
    image: postgres:14.11
    container_name: user_management
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_management
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d user_management"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-management-service:
    build: .
    image: wellu-user-management-service
    container_name: user-management-service
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://userdb:5432/user_management
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      userdb:
        condition: service_healthy

volumes:
  postgres-data: